---
- name: Setting up ubuntu 18.04 client
  hosts: client
  become: yes
  tasks:

  - name: Adding user 'geek-dev' with shell and group "developers'
    ansible.builtin.user:
      name: geek-dev
      shell: /bin/bash
      groups: developers
      append: yes
  
  - name: Adding user 'geek-ops' with shell and group "developers'
    ansible.builtin.user:
      name: geek-ops
      shell: /bin/bash
      groups: developers
      append: yes

  - name: Adding user 'geek-ops' to sudoers
    lineinfile:
      dest: /etc/sudoers
      regexp: '^geek-ops'
      line: 'geek-ops ALL=(ALL) NOPASSWD: ALL'
      state: present
      validate: 'visudo -cf %s'
  
  # - name: Get authorized keys for user 'geek-ops'
  #   ansible.posix.authorized_key:
  #     user: geek-ops
  #     state: present
  #     key: http://192.168.61.20/geek-ops.key.pub

  # - name: Test server connection
  #   ansible.netcommon.net_ping:
  #     dest: 192.168.61.20
  #     count: 2
