---
- name: Setting up ubuntu 18.04 client
  hosts: client
  become: yes
  tasks:

  - name: Adding user 'geek-dev' with shell and group "developers'
    hosts: client
    ansible.builtin.user:
      name: geek-dev
      shell: /bin/bash
      groups: developers
      append: yes

  - name: Test client connection
    ansible.netcommon.net_ping:
      dest: 192.168.61.21
      count: 2
