---
- hosts: test
  become: yes
  tasks:
    - name: Print Hello message
      debug:
        msg: Hello, Geek World!

    - name: Install Neofetch on Eurolinux9
      apt:
        name:
          - neofetch
        state: present

    - name: Adding user 'test-ops' with shell and group "developers'
      ansible.builtin.user:
        name: geek-ops
        shell: /bin/bash
        groups: developers
        append: yes

    - name: Create ssh key for user 'test-ops'
      ansible.builtin.user:
        name: test-ops
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/test-ops_key
