---
- name: Welcome message and general ansible run test
  hosts: all
  become: yes
  tasks:

    - name: Print Hello message
      debug:
        msg: Hello, Geek World!

    - name: Create developers group
      ansible.builtin.group:
        name: developers
        state: present
    
- name: Server setup playbook
  ansible.builtin.import_playbook: server.yml
  

- name: Client setup playbook
  ansible.builtin.import_playbook: client.yml