---
- hosts: all
  become: yes
  tasks:
    - name: Print Hello message
      debug:
        msg: Hello, Geek World!

    - name: Add the user
      ansible.builtin.user:
        name: geek
        comment: Homework_8
    
    - name: Update cache install apps
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - curl
        - net-tools
        - nmap
        - mtr
        - socat
