---
- name: Welcome message and general ansible run test
  hosts: all
  tasks:
    - name: Print Hello message
      debug:
        msg: Hello, Geek World!

    # - name: Test connection between labs machines
    #   ansible.netcommon.net_ping:
    #     dest: 192.168.60.11
    #     count: 2

    # - name: Test connection between labs machines
    #   ansible.netcommon.net_ping:
    #     dest: 192.168.60.12
    #     count: 2
 
# - name: Install Neofetch on Centos 7
#   become: yes
#   hosts: web
#     yum:
#       name:
#         - neofetch
#       state: present
  
    # - name: Test connection between labs machines
    #   hosts: web
    #   ansible.netcommon.net_ping:
    #     dest: 192.168.60.12
    #     count: 2

# - name: Install Neofetch on Ubuntu
#   become: yes
#   hosts: lab
#     apt:
#       name:
#         - neofetch
#       state: present
  
    # - name: Test connection between labs machines
    #   hosts: lab
    #   ansible.netcommon.net_ping:
    #     dest: 192.168.60.11
    #     count: 2

#     ---
# - hosts: all
#   become: yes

#   tasks:
#   - name: Update Alpine
#     command: apk upgrade -U -a

#   - name: Create developers group
#     ansible.builtin.group:
#       name: developers
#       state: present

#   - name: Adding user 'geek' with shell and group "developers'
#     ansible.builtin.user:
#       name: geek
#       shell: /bin/bash
#       groups: developers
#       append: yes

#   - name: Create ssh key for user 'geek'
#     ansible.builtin.user:
#       name: geek
#       generate_ssh_key: yes
#       ssh_key_bits: 2048
#       ssh_key_file: .ssh/geek_key
