---
- name: Setting up alpine server
  hosts: server
  become: yes
  tasks:

  - name: Adding user 'geek-ops' with shell and group "developers'
    ansible.builtin.user:
      name: geek-ops
      shell: /bin/bash
      groups: developers
      append: yes

  - name: Create ssh key for user 'geek'
    ansible.builtin.user:
      name: geek-ops
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/geek_key

  # - name: Test client connection
  #   ansible.netcommon.net_ping:
  #     dest: 192.168.61.21
  #     count: 2