---
- hosts: all
  become: yes
  tasks:
    - name: Print Hello message
      debug:
        msg: Hello, Geek World!

    - name: Apache installation
      community.general.apk:
        name: apache2
        state: present

    - name: Start service apache, if not started
      ansible.builtin.service:
        name: apache2
        state: started

    - name: Copy index.html
      ansible.builtin.copy:
        src: ./index.html
        dest: /var/www/localhost/htdocs/index.html
        owner: root
        group: root
        mode: '0644'
