# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    # alpine 3.17 with python 3.10 plus apache2
    config.vm.define "web" do |web|
      web.vm.box = "alpine317-py-repack"
      web.vm.synced_folder '.', '/vagrant'
      web.ssh.insert_key = false
  
      web.vm.provider "virtualbox" do |v|
        v.name = "apache01-geek"
        v.memory = 1024
        v.cpus = 1
      end
  
      web.vm.hostname = "apache01-geek"
      web.vm.network :private_network, ip: "192.168.60.11"
      web.vm.network "forwarded_port", guest: 80, host: 8181 

      web.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.become = true
      end
    end
  end