# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    # General Vagrant VM configuration
    config.vm.box = "alpine317py"
    config.vm.synced_folder '.', '/vagrant'
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.linked_clone = true
    end
    
    # Apache web server 1.
    config.vm.define "apachai14" do |web|
      web.vm.hostname = "apachai14-geek"
      web.vm.network :private_network, ip: "192.168.60.14"
      web.vm.network "forwarded_port", guest: 80, host: 8014
    end
    
    # Apache web server 2.
    config.vm.define "apachai15" do |web|
      web.vm.hostname = "apachai15-geek"
      web.vm.network :private_network, ip: "192.168.60.15"
      web.vm.network "forwarded_port", guest: 80, host: 8015
    end
    
    # Apache web server 3.
    config.vm.define "apachai16" do |web|
      web.vm.hostname = "apachai16-geek"
      web.vm.network :private_network, ip: "192.168.60.16"
      web.vm.network "forwarded_port", guest: 80, host: 8016
    end
    
    # Load balancer NGINX.
    config.vm.define "nginx17" do |web|
      web.vm.hostname = "nginx17-geek"
      web.vm.network :private_network, ip: "192.168.60.17"
      web.vm.network "forwarded_port", guest: 80, host: 8017
    end

    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.become = true
    end
  # vagrant global-status --prune
  end
