# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "server" do |server|
    server.vm.box = "ubuntu2204"
    server.vm.hostname = "ubuntu-geek"
    server.vm.network "private_network", ip: "192.168.60.13"
    server.vm.network "forwarded_port", guest: 80, host: 8113
    server.vm.network "forwarded_port", guest: 9000, host: 9013
    server.vm.synced_folder "./", "/vagrant"
  
    server.vm.provider "virtualbox" do |v|
      v.name = "ubuntu-geek"
      v.memory = 2048
      v.cpus = 1
    end
    
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    end
  end
end