---
- hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: Print Hello message
      debug:
        msg: Hello, Geek World!

    - name: Install MySQL server
      shell: apt-get -y install mysql-server

    - name: Install MySQL client
      shell: apt-get -y install mysql-client

    - name: Start the MySQL service
      action: service name=mysql state=started
